### ISSUE TITLE
One test fails with Django 1.6.10

### ISSUE THREAD

**Issue by AndersenTobias** [disqus/gutter-django#10]
```
Traceback (most recent call last):
  File "/home/vagrant/gutter-django/tests/test_nexus_modules.py", line 29, in test_index_works
    self.module.index(self.request)
  File "/home/vagrant/gutter-django/gutter/django/nexus_modules.py", line 93, in index
    return self.__render(request)
  File "/home/vagrant/gutter-django/gutter/django/nexus_modules.py", line 90, in __render
    return self.render_to_response(template, context, request)
  File "/usr/local/lib/python2.6/dist-packages/nexus/modules.py", line 82, in render_to_response
    context.update(self.get_context(request))
  File "/usr/local/lib/python2.6/dist-packages/nexus/modules.py", line 95, in get_context
    'trail_bits': self.get_trail(request),
  File "/usr/local/lib/python2.6/dist-packages/nexus/modules.py", line 125, in get_trail
    (self.get_title(), self.get_home_url(request)),
  File "/usr/local/lib/python2.6/dist-packages/nexus/modules.py", line 135, in get_home_url
    home_url = reverse(home_url_name, current_app=self.name)
  File "/usr/local/lib/python2.6/dist-packages/django/core/urlresolvers.py", line 507, in reverse
    app_list = resolver.app_dict[ns]
  File "/usr/local/lib/python2.6/dist-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/usr/local/lib/python2.6/dist-packages/django/core/urlresolvers.py", line 267, in _populate
    for pattern in reversed(self.url_patterns):
  File "/usr/local/lib/python2.6/dist-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.6/dist-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.6/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/gutter-django/example_project/urls.py", line 1, in <module>
    from django.conf.urls.defaults import *
ImportError: No module named defaults
```
Should I make a pull request about this?

**Comment by tail** [comment]
Fixed by 92e2e73a6e9173fd16a103f16314dbb8d643644b.
